### ISSUE TITLE
Broken for border properties

### ISSUE THREAD

**Issue by jpnelson** [ben-eb/postcss-merge-longhand#21] opened 2016-03-03 00:24 UTC
```
border-top-width: 1px;
  border-right-width: 1px;
  border-bottom-width: 1px;
  border-left-width: 1px;
```

is not the same as

```
border: 1px;
```

as this could remove other border properties that are set.

**Comment by joscha** [comment] 2016-03-03 00:29
probably duplicate of #20.

**Comment by ben-eb** [comment] 2016-03-03 00:33
OK, no problem; I know that the ideal result is `border-width:1px`, but it won't be fixed in this module as it is being refactored out of version 4. In its place I'm planning individual modules for property normalization/merging.

For now you can disable the module if it is causing any issues (or use the shorthand way of defining this).

**Comment by joscha** [comment] 2016-03-03 00:35
is there docs on how to disable it?

**Comment by jpnelson** [comment] 2016-03-03 00:36
we're using gulp-cssnano,

```
gulpCssnano({mergeLonghand: false})
```

is sufficient

**Comment by ben-eb** [comment] 2016-03-03 00:37
Yep, for future reference the transforms are documented here too. http://cssnano.co/options/

**Comment by seancurtis** [comment] 2016-03-03 00:49
Commented on the CSS Nano repo too, but including here to show the effect.

Current behaviour (too generic): http://jsbin.com/bakupi/edit?html,css,output
Expected behaviour: http://jsbin.com/bakupi/edit?html,css,output

**Comment by ben-eb** [comment] 2017-02-23 10:58
Resolved in [3.0](https://github.com/ben-eb/postcss-merge-longhand/commit/947185b1b19549410f943e2c24184e809746e231).

**Closed by ben-eb** 2017-02-23 10:58 UTC
